### PR TITLE
[tenant-namespace-operator] Upgraded to Operator SDK v1.4.0

### PR DESCRIPTION
**Pull request by plnordquist**
- Migrated to new directory structure
- Upgraded crds to apiextensions v1
- Added probes to chart
- Updated entrypoint for new docker image
- Fixed references to meta in ansible role

### CODE REVIEW

**Comment by plnordquist** [comment]
Marked as Draft until I can test upgrading from the older CRD definition and older deployment.  Tested and works with new resources.

**Comment by plnordquist** [comment]
Tested upgrading from older CRDs and chart version.  Ansible reported zero changes when upgrading the chart.  I think the CRD validation changes could complain about missing data if we put anything outside of spec or status but I think that would be an error anyways on our part.

**Comment by plnordquist** [comment]
I've rebased this and re-tested after the rebase.  I didn't find any issues with upgrades or new resources after deploying the new operator.  The CRD concerns above were already addressed when the CRDs were merged outside of this PR to upgrade them to apiextensions.k8s.io/v1.

**Review by kfox1111 — APPROVED** [review]
LGTM. Thanks! :)

**Pull request merged**
